# Generated by Django 5.0.4 on 2024-05-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name', 'company')},
        ),
    ]
